import Head from "next/head";

export default () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>SyncSwift 2022</h1>
      </main>
    </>
  );
};
