import Head from "next/head";

import Header from "./components/Header";
import Description from "./components/Description";
import Info from "./components/Info";

import style from "../styles/modules/BackgroundImage.module.css";

const Home = () => {
  return (
    <>
      <Head>
        <title>SyncSwift 2022</title>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        ></meta>
        <meta name="description" content="Generated by SyncSwift 2022" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={style.backgroundImage}>
        <Header></Header>
        <Description></Description>
        <Info></Info>

        <style jsx>{`
          main {
            width: 100vw;
            height: 100vh;
          }
        `}</style>
      </main>
    </>
  );
};

export default Home;
