import Head from "next/head";
import Image from "next/image";
import logoFile from "../public/AsyncSwiftLogo.svg";
import { Animated, Basic, bounce, Combined } from "../shared/styles";

export default function Home() {
  return (
    <>
      <Head>
        <title>SyncSwift 2022</title>
        <meta name="description" content="Generated by SyncSwift 2022" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Image
          src={logoFile}
          alt="AsyncSwift Community Logo"
          width={250}
          height={250}
        />
        <h1>SyncSwift Conference</h1>
        <h2>2022 11. 12</h2>
      </main>
    </>
  );
}
